### ISSUE TITLE
Hacktoberfest: Podcast search demo update

### ISSUE THREAD

**Issue by iamleonie** [weaviate-tutorials/DEMO-semantic-search-podcast#1]
This is the tracker for polishing the “Podcast search” demo. Please refer to our [Hacktoberfest 2023 blog](https://weaviate.io/blog/hacktoberfest-2023) if you want to contribute! 

List of items to contribute:

- [x]  Run the existing demo and identify and document what exists and what is or isn’t working for the next task
- [x]  Fixes for any of the identified issues (claimed by @IamSenthilKumar )
    - [x] UnicodeDecodeError in the import.py and added requirements.txt 
    - [x] added requirements.txt
- [ ]  Update README to include:
    - [ ] Short description
    - [x] used technology
        - [ ] used Weaviate modules/ML models
    - [ ]  demo video
    - [ ] Prerequisites
    - [x] Setup instructions
    - [x] Usage instructions
    - [x] Dataset license if applicable
- [ ] Possible improvements/enhancements
    - [x] Add progress bar to import file (claimed by @MomirMilutinovic )
    - [ ] Add front-end
    - [ ] Option to generate transcripts from podcast audio (e.g. with Whisper / wav2vec) (claimed by @IamSenthilKumar)
    - [ ] Vectorize entire podcast - allow searches of entire podcasts
    - [ ] Vectorize chunks - allow searches of sections / extracts
    - [ ] Clustering sections of podcast
    - [ ] Adding tests (e.g., Pytest, Jest, etc. See our [example](https://github.com/databyjp/distyll) for a starting point)
    - [ ] Conversion to new [Weaviate Python client](https://weaviate.io/blog/collections-python-client-preview) (claimed by @miniMaddy)
        - [ ] After Weaviate release 1.22: swap out preview image
    - [ ] Optional: Conversion to JavaScript (claimed by @srini047)

**We're open to further suggestions. If you have any further potential improvement ideas, let us know in the comments!**

📣You can contribute parts of the issue or the whole issue. Please comment below to volunteer for the part(s) you want to contribute to.

❓For any questions you might have along the way, join our [Discourse community forum](https://forum.weaviate.io/t/welcome-to-hacktoberfest-2023/764), where we're ready to answer your questions. Or join our dedicated #hacktoberfest channel in our [Weaviate Community Slack](https://weaviate.slack.com/) channel to stay connected and receive real-time support.

✅For your PR, please mention this issue and set @iamleonie as the reviewer and we will review your PR shortly.

**Comment by srini047** [comment]
Hi, I would like to try converting the current implementation to `JavaScript`. 
If that's in the scope then I would like to take it up.

**Comment by iamleonie** [comment]
@srini047 Yes, that's definitely in the scope and would be awesome! Thank you. Please don't hesitate to reach out via Slack or our forum if you need any assistance.

**Comment by tdubon** [comment]
Hi, I'm working on the Python implementation.

**Comment by Sankalpa-Acharya** [comment]
Hi, I will add the frontend.

**Comment by iamleonie** [comment]
Hey @tdubon, could you please let us know which parts of the Python implementation you are working on to avoid any code conflicts with @Sankalpa-Acharya.

**Comment by miniMaddy** [comment]
Hello @tdubon, are you working on the conversion to new weaviate Python client? I would like to take that up.

**Comment by tdubon** [comment]
Hi Madhav, no, I'm not. Please feel free to do so.

**Comment by miniMaddy** [comment]
Okay, I will be working on conversion to new weaviate client then.

**Comment by iamleonie** [comment]
Hi @miniMaddy, @Sankalpa-Acharya, @srini047,
to get a better overview for new contributors of which tasks already have people working on them I added your names to some tasks in the issues description.

Kindly, review if my understanding is correct and please let me know if I need to change something. Also, if you want to switch to a different task, don't hesitate to ping me and we will "unclaim" the task :)

Hey @tdubon, 
from the conversation, I couldn't figure out which parts you are working on in the Python implementation. Could you please let us know if you are working on any of the tasks and if yes, which ones?

Thank you guys so much for collaborating on this!

**Comment by Senthi1Kumar** [comment]
Hi, I would like to take generate transcripts from the podcast audio.

**Comment by tdubon** [comment]
Hi all, I've already completed 2 Jupyter notebooks and updated the .yml file for this demo. I've pushed the changes to the main branch but you won't see it until it's reviewed and approved. If you want to see it in the meantime, you can find it here: https://github.com/tdubon/DEMO-semantic-search-podcast

The video is missing. Also, I don't have OpenAI credits to see the outputs so if anyone wants to take this up, please let me know. Otherwise I'll have to find another way to test it.

**Comment by iamleonie** [comment]
Hey @Sankalpa-Acharya, @srini047, @IamSenthilKumar, and @miniMaddy ,
since it's the last week of Hacktoberfest, I wanted to quickly check in with you to see how things are going.
Please don't hesitate to reach out here or on our [Community Slack](https://weaviate.io/slack) if you need any assistance.
We can also un-claim the tasks if you are no longer working on the tasks.

**Comment by Senthi1Kumar** [comment]
Hi @iamleonie,

I ran the existing demo and I have fixed the `UnicodeDecodeError` in the `import.py` file by specifying the `encoding='utf-8'` parameter when loading the `data/podcast_ds.json` file. And everything works fine as per the setup and usage instructions w/ eg. queries.

For generating transcripts, I am using OpenAI's Whisper model and experimenting with it as the podcast duration varies from each other. For the podcast audio data, I think it would be best to use recent episodes of different podcasts shows from **Changelog**, as this will give a good mix of different audio qualities and duration.

**Comment by miniMaddy** [comment]
Hello @iamleonie , I am trying the solution where I chunk the data and store in the database. I will create a pull request soon.

**Comment by MomirMilutinovic** [comment]
Hi, I would like to add a progress bar to `import.py`.

**Comment by Sankalpa-Acharya** [comment]
Hi, I'm sorry, but I'm not working on this task. You can unclaim it

**Comment by iamleonie** [comment]
Thank you, everyone, for contributing to a successful Hacktoberfest 2023!

This issue will now be closed.

If you are still working on any topics, you can, of course, continue on them. However, please note that any PRs created after Oct 31st will not count towards Hacktoberfest.
